version: "3"

services:
  app:
    image: node:latest
    build: .
    volumes:
      - ".:/src"
    command: npm start
    depends_on:
      - rabbit1
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
   
    labels:
      NAME: "rabbitmq1"
   
