version: "3"

services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: ${RABBIT_HOSTNAME}
    env_file: ".env"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
  server:
    build: server/
    image: server
    env_file: ".env"
    command: ./wait-for.sh rabbit:15672 -- npm run start
    # restart: unless-stopped
    depends_on: 
      - rabbit